---
title: "Tools to study round-the-clock hospital medicine"
author: "Marc Ruben"
date: "7/8/2019"
output: github_document
---

In a recent study <https://www.biorxiv.org/content/10.1101/617944v1>  we analyzed the daily distribution of ~120K doses of 12 separate drugs in ~1.5K inpatients at a major children’s hospital in the U.S. Treatment orders and administration were strongly time-of-day-dependent, marked by distinct morning time surges and overnight lulls. These 24 h rhythms in treatment were consistent across drugs, diagnoses, and hospital units.

**This repository contains the code used for each part of this study: (1) extract patient data (EMR) and evaluating daily (2) distribution of treatment, and (3) patterns of response**

## Part 1. Extract EMR data from Epic
This repository describes how to extract patient data from Epic. Explain that some adaptation of this code may be necessary depending upon the Epic systems at user's institution.

## Part 2. Evaluate 24 h patterns in TREATMENT
Summarise the objective and methodology. Describe the code that is provided

## Part 3. Evaluate 24 h patterns in RESPONSE
Summarise the objective and methodology. Describe the code that is provided